version: "3.9"
services: 
    server:
        build: .
        ports:
            - "5000:5000"
        environment:
            FLASK_ENV: development
    front-end:
        build: 
            context: ./react-frontend-app
            dockerfile: Dockerfile
        ports:
            - "3000:3000"