version: "3.8"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
        FLASK_ENV: development
  front-end:
    build: 
      context: ./react-frontend-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./react-frontend-app:/app
      - /app/node_modules